orbs: # declare what orbs we are going to use
    node: circleci/node@2.0.2 # the node orb provides common node-related configuration

version: 2.1 # using 2.1 provides access to orbs and other features

jobs:
    test:
        docker:
            - image: cimg/node:16.8.0
        steps:
            - checkout
            - run: npm install # directs the test case to install npm
            - run: npm run test # directs the test case to run the test cases

workflows: 
    app-tests: # names the this specifc workflow
        jobs: # lists the order of jobs to be completed
            - test # names which specific test to be done
            - it # run the second test I put in